version: '3.1'
services:
  mongo:
    image: mongo:latest
    env_file: .env
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
  mongo-express:
    image: mongo-express:latest
    env_file: .env
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
  osd-perm:
    image: ghcr.io/mertdogan12/osd-perm:latest
    env_file: .env
    restart: always
    ports:
      - 3000:80

